"use client";

import { useEffect, useMemo, useState } from "react";
import { addPackage, groupStops, makeDemoRoute, progress, type RouteState } from "../lib/domain";
import { loadRoute, saveRoute } from "../lib/offline-store";
import { optimizeStops, routeDistance } from "../lib/routing/local-optimizer";

type View = "dashboard" | "scan" | "optimize" | "drive" | "summary";
const icons: Record<string, string> = { dashboard: "⌂", routes: "↗", scan: "⌗", history: "◷", more: "•••" };

export function BeepRouteApp() {
  const [route, setRoute] = useState<RouteState | null>(null);
  const [view, setView] = useState<View>("dashboard");
  const [code, setCode] = useState("");
  const [notice, setNotice] = useState("");
  const [online, setOnline] = useState(true);
  const [ready, setReady] = useState(false);

  useEffect(() => { loadRoute().then((saved) => { if (saved) setRoute(saved); setReady(true); }).catch(() => setReady(true)); const sync = () => setOnline(navigator.onLine); sync(); addEventListener("online", sync); addEventListener("offline", sync); if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined); return () => { removeEventListener("online", sync); removeEventListener("offline", sync); }; }, []);
  useEffect(() => { if (route && ready) void saveRoute(route); }, [route, ready]);
  const metrics = useMemo(() => route ? progress(route) : { total: 0, delivered: 0, failed: 0, pending: 0 }, [route]);
  const activeStop = route?.stops.find((stop) => stop.status === "pending" || stop.status === "skipped");

  function createRoute() { setRoute(makeDemoRoute()); setView("scan"); }
  function scan(value = code) { if (!route || !value.trim()) return; const result = addPackage(route, value); if (result.duplicate) setNotice(`⚠ Pacote ${value.toUpperCase()} já bipado`); else { setRoute(result.route); setNotice("✓ Pacote adicionado"); setCode(""); navigator.vibrate?.(70); } }
  function addDemo() { scan(`BR-DEMO-${String((route?.packages.length ?? 0) + 1).padStart(3, "0")}`); }
  function optimize() { if (!route?.packages.length) return; const stops = optimizeStops(groupStops(route.packages), route.origin); setRoute({ ...route, status: "optimized", stops }); setNotice("✓ Rota otimizada localmente"); setView("optimize"); }
  function startRoute() { if (!route) return; setRoute({ ...route, status: "in_progress", startedAt: route.startedAt ?? new Date().toISOString() }); setView("drive"); }
  function finishStop(failed = false) { if (!route || !activeStop) return; const stopPackages = new Set(activeStop.packages.map((item) => item.id)); const packages = route.packages.map((item) => stopPackages.has(item.id) ? { ...item, status: failed ? "failed" as const : "delivered" as const } : item); const stops = route.stops.map((item) => item.id === activeStop.id ? { ...item, status: failed ? "failed" as const : "completed" as const } : item); const hasPending = stops.some((item) => item.status === "pending" || item.status === "skipped"); setRoute({ ...route, packages, stops, status: hasPending ? "in_progress" : "completed", completedAt: hasPending ? undefined : new Date().toISOString() }); setNotice(failed ? "Problema registrado. Seguindo rota." : "✓ Entrega concluída"); if (!hasPending) setView("summary"); }
  function skipStop() { if (!route || !activeStop) return; const stops = route.stops.map((item) => item.id === activeStop.id ? { ...item, status: "skipped" as const, sequence: route.stops.length + 1 } : item).sort((a, b) => (a.status === "skipped" ? 1 : 0) - (b.status === "skipped" ? 1 : 0)).map((item, index) => ({ ...item, sequence: index + 1 })); setRoute({ ...route, stops }); setNotice("Entrega movida para o fim"); }
  function openMap(kind: "waze" | "google") { if (!activeStop) return; const destination = `${activeStop.latitude},${activeStop.longitude}`; location.href = kind === "waze" ? `https://waze.com/ul?ll=${destination}&navigate=yes` : `https://www.google.com/maps/dir/?api=1&destination=${destination}&travelmode=driving`; }

  if (!ready) return <main className="loading-shell"><div className="skeleton wide"/><div className="skeleton card"/><div className="skeleton card"/></main>;
  return <div className="app-frame">
    <aside className="sidebar"><Brand/><p className="side-label">TRABALHO</p>{[["dashboard","Início"],["routes","Rotas"],["scan","Bipar"],["history","Histórico"]].map(([key,label]) => <button key={key} className={view === key ? "side-link active" : "side-link"} onClick={() => setView(key === "scan" && route ? "scan" : "dashboard")}><span>{icons[key]}</span>{label}</button>)}<div className="side-foot"><span className="avatar">AN</span><div><b>André</b><small>Modo demonstração</small></div></div></aside>
    <main className="main"><header className="topbar"><Brand/><div className="top-actions">{!online && <span className="offline">● Sem conexão</span>}<span className="demo-pill">DEMO</span><button className="icon-button" aria-label="Notificações">♢</button><span className="avatar">AN</span></div></header>
      {notice && <button className="toast" onClick={() => setNotice("")}>{notice}<span>×</span></button>}
      {view === "dashboard" && <Dashboard route={route} metrics={metrics} onCreate={createRoute} onContinue={() => setView(route?.status === "in_progress" ? "drive" : "scan")}/>} 
      {view === "scan" && route && <Scan route={route} code={code} setCode={setCode} scan={() => scan()} addDemo={addDemo} optimize={optimize}/>} 
      {view === "optimize" && route && <Optimize route={route} start={startRoute}/>} 
      {view === "drive" && route && activeStop && <Drive route={route} stop={activeStop} delivered={() => finishStop()} failed={() => finishStop(true)} skip={skipStop} openMap={openMap}/>} 
      {view === "summary" && route && <Summary route={route} metrics={metrics} home={() => setView("dashboard")}/>} 
      {(view !== "dashboard" && !route) && <Dashboard route={null} metrics={metrics} onCreate={createRoute} onContinue={() => undefined}/>} 
    </main>
    {view !== "drive" && <nav className="bottom-nav">{[["dashboard","Início"],["routes","Rotas"],["scan","Bipar"],["history","Histórico"],["more","Mais"]].map(([key,label]) => <button key={key} className={view === key ? "active" : ""} onClick={() => setView(key === "scan" && route ? "scan" : "dashboard")}><span>{icons[key]}</span>{label}</button>)}</nav>}
  </div>;
}

function Brand() { return <div className="brand"><span className="brand-mark">⌁</span><strong>Beep <em>Route</em></strong></div>; }
function Dashboard({ route, metrics, onCreate, onContinue }: { route: RouteState | null; metrics: ReturnType<typeof progress>; onCreate: () => void; onContinue: () => void }) { const pct = metrics.total ? Math.round(metrics.delivered / metrics.total * 100) : 0; return <section className="page dashboard"><div className="greeting"><div><p>TERÇA-FEIRA, 18 DE AGOSTO</p><h1>Olá, André <span>👋</span></h1><h2>Pronto para as entregas de hoje?</h2></div><button className="primary desktop-create" onClick={onCreate}>＋ Nova rota</button></div>{route ? <article className="route-hero"><div className="route-hero-head"><span className="hero-icon">↗</span><div><small>ROTA DE HOJE</small><h3>{route.name}</h3></div><span className="status">{route.status === "in_progress" ? "EM ANDAMENTO" : "EM PREPARAÇÃO"}</span></div><div className="progress-row"><strong>{metrics.delivered} de {metrics.total} pacotes</strong><span>{pct}% concluído</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="route-stats"><div><small>PENDENTES</small><b>{metrics.pending}</b></div><div><small>ENTREGUES</small><b className="green">{metrics.delivered}</b></div><div><small>PROBLEMAS</small><b className="red">{metrics.failed}</b></div><div><small>DISTÂNCIA</small><b>{route.stops.length ? `${(routeDistance(route.stops, route.origin)/1000).toFixed(1)} km` : "—"}</b></div></div><button className="continue" onClick={onContinue}>Continuar rota <span>→</span></button></article> : <article className="empty-route"><span className="hero-icon">↗</span><h3>Nenhuma rota em andamento</h3><p>Crie sua primeira rota e comece a bipar as encomendas.</p><button className="primary" onClick={onCreate}>＋ Nova rota</button></article>}<h3 className="section-title">Resumo de hoje</h3><div className="metric-grid">{[["▣","Pacotes hoje",metrics.total,"teal"],["✓","Entregues",metrics.delivered,"green"],["⌁","Km percorridos",route?.stops.length ? (routeDistance(route.stops, route.origin)/1000).toFixed(1) : "0,0","blue"],["◷","Pendentes",metrics.pending,"amber"]].map(([icon,label,value,color]) => <article className="metric" key={String(label)}><span className={`metric-icon ${color}`}>{icon}</span><small>{label}</small><strong>{value}</strong><em>{label === "Entregues" && metrics.total ? `${Math.round(metrics.delivered/metrics.total*100)}% do total` : "Atualizado agora"}</em></article>)}</div><div className="recent-head"><h3 className="section-title">Histórico recente</h3><button>Ver tudo →</button></div><article className="history-row"><span className="date-box"><b>17</b><small>AGO</small></span><div><b>Rota 17/08/2026</b><small>Concluída • 38 pacotes</small></div><div className="history-meta"><b>36 entregues</b><small>2 problemas · 54,8 km</small></div><span>›</span></article></section>; }
function Scan({ route, code, setCode, scan, addDemo, optimize }: { route: RouteState; code: string; setCode: (v:string)=>void; scan:()=>void; addDemo:()=>void; optimize:()=>void }) { return <section className="page narrow"><div className="page-title"><div><small>CARREGANDO ROTA</small><h1>{route.name}</h1></div><span className="status">EM PREPARAÇÃO</span></div><article className="scan-card"><span className="scan-count">{route.packages.length}</span><h2>{route.packages.length === 1 ? "pacote bipado" : "pacotes bipados"}</h2><p>A câmera real usa BarcodeDetector quando disponível; no demo, adicione etiquetas simuladas ou digite o código.</p><button className="primary jumbo" onClick={addDemo}>⌗ Bipar encomenda demo</button><div className="manual"><input value={code} onChange={(e)=>setCode(e.target.value)} onKeyDown={(e)=>e.key === "Enter" && scan()} placeholder="Código da encomenda" aria-label="Código da encomenda"/><button onClick={scan}>Adicionar</button></div></article><div className="list-head"><h3>Últimos pacotes</h3><button onClick={optimize} disabled={!route.packages.length}>Preparar rota →</button></div><div className="package-list">{route.packages.map((pack)=><article key={pack.id}><span className="package-icon">▣</span><div><b>{pack.trackingCode}</b><small>{pack.address}</small></div><span className="check">✓</span></article>)}</div></section>; }
function Optimize({ route, start }: { route: RouteState; start:()=>void }) { const km=(routeDistance(route.stops,route.origin)/1000).toFixed(1); return <section className="page narrow"><div className="ready-title"><span>✓</span><div><small>OTIMIZAÇÃO APROXIMADA</small><h1>Rota pronta</h1><p>Vizinho mais próximo + melhoria 2-opt</p></div></div><div className="route-ready-stats"><div><b>{route.packages.length}</b><small>pacotes</small></div><div><b>{route.stops.length}</b><small>paradas</small></div><div><b>{km}</b><small>km estimados</small></div></div><div className="map"><div className="route-line"/>{route.stops.map((stop,i)=><span className="pin" key={stop.id} style={{left:`${18+(i%3)*30}%`,top:`${22+(i%2)*42}%`}}>{i+1}</span>)}<span className="origin">BASE</span></div><div className="stop-list"><h3>Sequência de entregas</h3>{route.stops.map((stop)=><article key={stop.id}><span>{stop.sequence}</span><div><b>{stop.address.split(" — ")[0]}</b><small>{stop.packages.length} {stop.packages.length===1?"pacote":"pacotes"}</small></div><i>≡</i></article>)}</div><button className="primary sticky-action" onClick={start}>🚗 INICIAR ROTA</button></section>; }
function Drive({ route, stop, delivered, failed, skip, openMap }: { route:RouteState; stop:RouteState["stops"][number]; delivered:()=>void; failed:()=>void; skip:()=>void; openMap:(k:"waze"|"google")=>void }) { const done=route.stops.filter(s=>s.status==="completed"||s.status==="failed").length; return <section className="drive"><div className="drive-top"><Brand/><span>{done+1} de {route.stops.length}</span></div><div className="progress"><i style={{width:`${done/route.stops.length*100}%`}}/></div><small>PRÓXIMA PARADA</small><h1>{stop.address.split(" — ")[0]}</h1><p>{stop.address.split(" — ")[1]}</p><div className="take"><h3>PEGAR {stop.packages.length} {stop.packages.length===1?"PACOTE":"PACOTES"}</h3>{stop.packages.map(pack=><div key={pack.id}><span>▣</span><b>{pack.trackingCode}</b><small>{pack.vehiclePosition}</small></div>)}</div><div className="nav-buttons"><button onClick={()=>openMap("waze")}>Abrir no Waze ↗</button><button onClick={()=>openMap("google")}>Google Maps</button></div><div className="drive-actions"><button className="delivered" onClick={delivered}>✓ ENTREGUE</button><div><button onClick={failed}>Não consegui entregar</button><button onClick={skip}>Fazer depois</button></div></div></section>; }
function Summary({ route, metrics, home }: { route:RouteState; metrics:ReturnType<typeof progress>; home:()=>void }) { return <section className="page summary"><span className="celebrate">✓</span><small>ROTA FINALIZADA</small><h1>Rota concluída!</h1><p>Bom trabalho. Todas as paradas foram processadas.</p><div className="summary-grid"><div><b>{metrics.total}</b><small>pacotes</small></div><div><b>{metrics.delivered}</b><small>entregues</small></div><div><b>{metrics.failed}</b><small>problemas</small></div><div><b>{route.stops.length}</b><small>paradas</small></div></div><button className="primary" onClick={home}>Voltar ao início</button></section>; }
